### ISSUE TITLE
Disable auto tracking on certain component ? Set page title from vue-meta title ?

### ISSUE THREAD

**Issue by darkylmnx** [MatteoGabriele/vue-gtag#113]
**This is a question / feature request**

I didn't see in the docs if it was possible to disable auto-tracking on specific components.
**Use Case** : Certain pages can have a title from remote data, so `pageView` would be sent after the component is loaded and therefore way after `router.afterEach`.

Also, is there an intergration with **vue-meta** in the pipe as it's the most used plugin for meta data?
**Use case**: Getting the title from the component's meta info function.
```javascript
export default {
  metaInfo() {
    return { title: `title part ${this.endTitle}` }
  },
  data() {
    return { endTitle: 'title part 2'}
  }
}
```

Question 1 could resolve Question 2 in a cheap manner as I would send manual pageViews when I need it based on reactive data.

**Comment by MatteoGabriele** [comment]
I will probably implement a way to skip a route, but can't skip a component.
this issue is already opened here #141 

for vue-meta, I am not sure how to help. I remember when working on vue-analytics that waiting for the nextTick was enough to get the title from the new rendered page. I still wait for the nextTick here too, so not sure why doesn't work.
