### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by cliqer** [MatteoGabriele/vue-gtag#168]
Hi and thank you for this plugin.
While trying to add analytics on vite and vue 3 being in RC3 I was wondering if you have any plans on supporting these.
Right now I'm getting:
```
Uncaught TypeError: Cannot set property '$gtag' of undefined
```
Many Thanks

**Comment by MatteoGabriele** [comment]
Hi @gianniskarmas 
to be honest I never tried Vite, so not sure why would need a special treatment and why throws the error, but for sure I will make sure to be ready for Vue 3. the framework it's in RC so there's time + I doubt people will start migrating applications from day 1 :)

**Comment by MatteoGabriele** [comment]
ok so I read that vite is a vue 3 app only so once gtag is updated, should all be good
thanks

**Comment by cjblomqvist** [comment]
As a suggestion @MatteoGabriele , keep this issue open until it works works with Vue 3.0, so that people don't miss the issue 😊

**Comment by MatteoGabriele** [comment]
Sure, makes sense

**Comment by cliqer** [comment]
It would also be nice if we had a 'vue-gtag-next' repository to work on the needed changes while under development just like vue, vue router etc.

**Comment by MatteoGabriele** [comment]
I have started working on version 2 of the plugin. 
The intention is to rewrite a better plugin using all the power of the new composition API as well which will allow the developer more control over it.
you can check the branch `v2` if you want, but it's in early stages.
I will provide a `vue-gtag@next` package when everything will be ready. Another repository is not necessary

**Comment by christopherchateau** [comment]
Is there any type of current workaround that would allow vue-gtag to be used in a Vue 3 project?

**Comment by MatteoGabriele** [comment]
@christopherchateau within the next 2 weeks I should have enough time to finish the vue-gtag plugin for vue3, but for now there's no way you can use the current version of the plugin in vue3, sorry

**Comment by MatteoGabriele** [comment]
so I think I almost got a stable-ish version.
I made quite a few changes and I will try to share some of them here before I finish testing, writing the doc and publish.

### installation
I published the vue3 version under `vue-gtag-next` package

```bash
yarn add vue-gtag-next
```
then install the library

```js
import { createApp } from "vue";
import App from "./App.vue";
import gtag from "vue-gtag-next";

const app = createApp(App)

app.use(gtag, {
  property: {
    id: 'UA-123456-7'
  }
})

app.mount("#app");
```

the `property` object is what in the current v2 version is the `config` object. ( shape is still `{ id: Number, params: Object }`
I have changed the name because of the conflict with the actual `config` gtag api.
now `property` can simply be an object or an array of objects for when we want to use multiple domain tracking.

### plugin options/state
default values
```
{
  property: null,
  isEnabled: true,
  globalObjectName: "gtag",
  globalDataLayerName: "dataLayer",
  domain: "https://www.googletagmanager.com",
  customResource: null,
  useDebugger: false,
}
```

### install automatic route tracking
I have separated the 2 features to make plugin a bit more easy to separate

install the application with vue-router

```js
import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import gtag from "vue-gtag-next";

const app = createApp(App);

app.use(router);
app.use(gtag, {
  property: {
    id: "UA-123456-7"
  }
});
app.mount("#app");
```

then in the router file, for example, you can use the `trackRouter` method, which also has option specifically for the automatic routing feature

```js
import { createRouter, createWebHistory } from "vue-router";
import Home from "../views/Home.vue";
import { trackRouter } from "vue-gtag-next";

const routes = [
  {
    path: "/",
    name: "Home",
    component: Home
  },
  {
    path: "/about",
    name: "About",
    component: () =>
      import(/* webpackChunkName: "about" */ "../views/About.vue")
  }
];

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes
});

trackRouter(router);

export default router;
```

#### trackRouter options
default values
```
{
  template: null,
  appName: null,
  useScreenview: false,
  skipSamePath: true,
}
```

### components 
the usage in components is exactly the same: you can access the `this.$gtag` object

### composition api
vue 3 obviously introduces the new composition api and this is actually the best part of the refactor: almost everything is reactive and it can be used and modified everywhere.

```html
<template>
  <div>
    <div v-if="!isTracking">
      <p>Click here if you agree with the tracking policy and blablabla</p>
      <button @click="addProperty">All good</button>
    </div>
    <router-view></router-view>
  </div>
</template>

<script>
import { isTracking, useState } from "vue-gtag-next";

export default {
  setup() {
    const { property } = useState();

    const addProperty = () => {
      property.value = {
        id: "UA-1234567-7"
      };
    };

    return {
      isTracking,
      addProperty
    };
  }
};
</script>
```

The `useState` returns refs that before could have been modified only from the plugin installation. This makes it easier, for example, to create a tracking banner and start tracking only after a user accepts the policy.


it is also possible to track using the `useGtag` function

```html
<template>
  <div>
    <button @click="login">Login</button>
  </div>
</template>

<script>
import { useGtag } from "vue-gtag-next";

export default {
  setup() {
    const { event } = useGtag()
    const login = () => {
      event('login', { method: 'Google' })
    }

    return {
      login
    };
  }
};
</script>
```

let me know if you have any questions. it's obviously still not ready to production and I am working on it + need to add all current features as well

**Comment by MatteoGabriele** [comment]
as actually suggested once, I moved the next-making to a new repo https://github.com/MatteoGabriele/vue-gtag-next and as you already know everything until completed is moved to the new package `vue-gtag-next`
all questions and issues can now be redirected in that repository.
gonna keep this open just as a reference and will close it when everything is finished.

I hope that you guys will have some time to play with it, now that you can also check the code to see what's possible and what not and have a better understanding of it

**Comment by MatteoGabriele** [comment]
just published a new update on the package `vue-gtag-next` v1.12.0 and I think it has all I needed to add. I am only missing tests and documentation which, as usual, will take more than the actual coding 🤣

**Comment by christopherchateau** [comment]
Is it necessary to add a vue-gtag-next.d.ts file in order to use this with typescript? 
Thanks for the new version!

**Comment by MatteoGabriele** [comment]
@christopherchateau to be honest I want to find a way to get the typescript file out of the repository, especially because I don't use typescript and don't want to judge a PR with typescript code for example.
If you have any ideas, I'm all ears.

Thanks

**Comment by MatteoGabriele** [comment]
Todo list

- [ ] migration
- [ ] tests
- [ ] documentation

**Comment by MatteoGabriele** [comment]
update: the typescript definition has been merged and published in the new version.
I am still working on finishing the documentation

**Comment by MatteoGabriele** [comment]
update: Just release the documentation for version 2 here https://matteo-gabriele.gitbook.io/vue-gtag/v/next/
some feedback would be much appreciated.
I hope I didn't miss anything.

**Comment by MatteoGabriele** [comment]
After a pretty long refactoring of the current version 1 using TDD, I could more easily switch between vue 2 and vue 3 and so vue-gtag@2 will first be an easier migration with the same API and options as vue-gtag@1 but with vue 3 support.
what's currently vue-gtag-next, will soon become vue-gtag@3 with the improved API and more vue 3 approach.

**Comment by MatteoGabriele** [comment]
I wrote a tiny article about the release [here](https://matteo-gabriele.medium.com/migrate-vue-gtag-to-vue-3-3cdb44765edd)
