### ISSUE TITLE
VueRouter set but gtag take browser page title

### ISSUE THREAD

**Issue by Bkl741** [MatteoGabriele/vue-gtag#240]
Hi,

I configure vue-gtag to use vuerouter but when I watch gtag query, browser page title is sent (not route name). When I debug plugin, parameters are set correctly : 

Configuration :

`Vue.use(VueGtag, {
  config: {
    id: "GTM-XXXXXXX"
  }
}, router);`

Parameters in vue-gtag : 
`
{
page_title : 'MyRouteName',
page_location :  'MyLocation',
page_path: 'MyPath'
}
`

I don't understand why...

My version of  vue-gtag is 1.10.0

Thank you for your help.

**Comment by MatteoGabriele** [comment]
You need to create a reproduction do that i can check. Please needs to be as simple as possible reproducing your issue

Thanks

**Comment by Bkl741** [comment]
I tried with another vue plugin. It seems that google tag manager override router title with browser page title.

When I debug your plugin, router name is sent to google tag manager but it's overrided inside the google library

**Comment by MatteoGabriele** [comment]
It is weird. Are u using an SPA or it's an SSR application? Don't know why should act differently but just to have the full picture

**Comment by Bkl741** [comment]
I'm using an spa

**Comment by bmc-at-hfi** [comment]
I'm having the same issue with my SPA. Similar to @Bkl741, I am using VueGtag with very few tweaks out of the box.

`Vue.use(VueGtag, {
  config: {
    id: "G-XXXXXXXXXXX"
  }
}, router);`

However, when I took a look at the page views that Google Analytics was collecting, I noticed that some came through with the route name, which is the vue-gtag default, but some came through with the webpage title (the gtag.js default behavior).

I dug into the vue-gtag code with a debugger and as best I could tell, the event was always being sent properly

`gtag("event", "page_view", {
  page_location: "http://localhost:3000/myroute",
  page_path: "/myroute",
  page_title: "myroute",
});`

But examining my network traffic, I spotted the page title in the GET request.
`https://www.google-analytics.com/g/collect?  ...   &dt=pagetitle&   ...`

Here were some things I found that may help you reproduce.
- I only observed this bug on initial page load. As the route changes after initialization of my SPA, it works as expected.
- I have a "per-route" guard on my routes. Removing the guard prevented the issue, but I need the guard in production. https://router.vuejs.org/guide/advanced/navigation-guards.html#per-route-guard
- There is an asynchronous component to the guard on initial page load, where we wait for comminication with our Auth provider to make sure user is logged in. 

Here's an example of my route config:
`{
  path: "/myroute",
  name: "myroute",
  component: myroute,
  beforeEnter: authGuard
}`

And here's the authGuard. authService is a Vue instance. My guess there is something related to me utilizing `$watch`, and waiting to call `next()`, but I could not pinpoint _why_ that would cause an issue.
`const authGuard = (to, from, next) => {
  const authService = getInstance();

  const fn = () => {
    if (authService.isAuthenticated) {
      return next();
    }

    authService.loginWithRedirect({ appState: { targetUrl: to.fullPath }});
  };

  if (!authService.loading) {
    return fn();
  }

  authService.$watch("loading", loading => {
    if (loading === false) {
      return fn();
    }
  });
};`

My current workaround is to use a custom `pageTrackerTemplate` in order to always use the Page Title on purpose... although I'd much prefer to track by route name.

**Comment by MatteoGabriele** [comment]
sorry for the ridiculously late response, but I tried a bunch of things and nothing: I always get the debugger or the request to analytics sending the right data.
unfortunately, I need a real reproduction with this issue highlighted.

please feel free to re-open this ticket if you find the way

thanks again for your feedback

**Comment by douglas-fabiano** [comment]
I also have the same problem.
When analyzing the requests I realized that the route name of the vue router is being sent, which is the correct one.
But the title of the page is also sent in the parameters, and when entering google analytics the two names are left.
This is only happening when I have the <title> tag in the html.

![image](https://user-images.githubusercontent.com/39135298/114273275-6cfdce80-99e7-11eb-8b14-d7265b44d580.png)
![image](https://user-images.githubusercontent.com/39135298/114273300-80109e80-99e7-11eb-8216-ab4f1b6b844a.png)

**Comment by MatteoGabriele** [comment]
@douglas-fabiano couldn't that be something that Google Analytics takes out of the box from the `document.title`? I'm going to check if there's a way to disable that manually

**Comment by MatteoGabriele** [comment]
So I removed names of my routes and the `page_view` was sent with `page_title: undefined`, but in the Hit Details, the `dt` (Document Title) property was filled with my page title.
I think there could be some problem with who-comes-first and so it sees a nullable value and applies the document title.
