### ISSUE TITLE
How to load script after disabling script loading?

### ISSUE THREAD

**Issue by lautiamkok** [MatteoGabriele/vue-gtag#289]
It seems that the [documentation](https://matteo-gabriele.gitbook.io/vue-gtag/custom-installation#disable-script-loading) is incomplete as it does not explain how to load the script after  disabling script loading:

```
import Vue from "vue";
import VueGtag from "vue-gtag";

Vue.use(VueGtag, {
  config: { id: "UA-1234567-1" },
  disableScriptLoad: true
});
```

So, how can we load the script on demand?

**Comment by MatteoGabriele** [comment]
it's probably because this feature is meant to be use only in situations where you already have a page that injects the analytics script for you and so you don't want to load it twice and create multiple trackers.
if you want to disable gtag and enable it after, you might want to use `enabled: false/true` or use the `bootstrap: false` and then bootstrap in another moment.

**Comment by MatteoGabriele** [comment]
I will close this issue due to inactivities, but please feel free to re-open it if you need more info
