### ISSUE TITLE
Send event - set category, label, etc

### ISSUE THREAD

**Issue by alex-parra** [MatteoGabriele/vue-gtag#52]
In the documentation for tracking events there's this code:
```
this.$gtag.event('login', { method: 'Google' })
```
but no information on how to set the event category, label, etc.
With the code above, the event shows in our analytics with category `general`, action `login` and nothing else.
I'm missing something, but haven't figured out what.
Thanks.

**Comment by jtrobinson1993** [comment]
This issue seems to address your question:

https://github.com/MatteoGabriele/vue-gtag/issues/50

As far as I can tell, the object in which you pass `method` should also be used to pass other parameters like category and label. The author of the library or someone else can correct me if I'm wrong.

**Comment by alex-parra** [comment]
🤦🏻‍♂️idiot me...
closing.

**Comment by MatteoGabriele** [comment]
yeah I have used the example that was in the google api but maybe I should drop one more example + the link to the API maybe to make things a bit more clear.

sometimes when you write documentation you're kinda writing it with a certain knowledge because you wrote the actual library, so I appreciate feedback so I can make it more generic and understandable for everyone
