### ISSUE TITLE
Consent cannot be used 【BUG】

### ISSUE THREAD

**Issue by zy598586050** [MatteoGabriele/vue-gtag#581]
![image](https://github.com/user-attachments/assets/23981273-8678-49e9-bca2-ed0ab70b72b8)

![image](https://github.com/user-attachments/assets/f7296ba2-d1f4-4dd5-8da2-de442396c068)

**The document clearly states' query ', but in reality, it does not**

https://developers.google.com/tag-platform/security/guides/consent?sjid=4394773096305478934-AP&hl=zh-cn#gtag.js_1

Cannot be achieved

"vue-gtag-next": "^1.14.0"

**Comment by MatteoGabriele** [comment]
you are using the wrong package. This is not vue-gtag-next repo, this is vue-gtag. 
you can see that `query` is indeed exported https://github.com/MatteoGabriele/vue-gtag/blob/master/src/index.js#L16
make sure to use vue-gtag instead of vue-gtag-next which was just a vue3 compatible version of the previous vue-gtag.
I know it's a bit confusing but the component was published during vue2 to vue3 migration period.
