### ISSUE TITLE
Not working when using `vue-cli-service build`

### ISSUE THREAD

**Issue by monisnap-julien** [MatteoGabriele/vue-gtag#88]
### Description

The plugin is not working when building a vue.js app using `vue-cli-service build`. There is an error displayed in console without much informations saying why it's not loading :

![image](https://user-images.githubusercontent.com/44771598/75237260-57b3e980-57bf-11ea-85f7-d0e308fbc460.png)

### Expected behavior

It should load or at least display why it's not loading.

### Actual behavior

Tell us what actually happens.

### Environment

I run `vue-cli-service build` then upload on a feature phone (KaiOS) that embed web content in iframes as application (Firefox OS).

**Comment by MatteoGabriele** [comment]
I have to be honest, you environment is pretty complex to understand.
what's KaiOS? then the iframe in a web content on firefox os... it's not that clear to me.
if you can replicate this issue in a more simple environment I will have a look, otherwise it's quite impossible to me to understand what to do.

**Comment by monisnap-julien** [comment]
I actually used a workaround so i can close this issue
